const ADD_POKEMON = "ADD_POKEMON";
const UPDATE_POKEMONS = "UPDATE_POKEMONS";
const CHANGE_FILTER = "CHANGE_FILTER";
const CHANGE_FILTER_LENGHT = "CHANGE_FILTER_LENGHT";
const PAGE_LOADED = "PAGE_LOADED";
const POKEMON_PAGE_LOADED = "POKEMON_PAGE_LOADED";
const LOADING = "LOADING";

export {
	ADD_POKEMON,
	UPDATE_POKEMONS,
	CHANGE_FILTER,
	CHANGE_FILTER_LENGHT,
	PAGE_LOADED,
	POKEMON_PAGE_LOADED,
  LOADING,
}
